Agrego componente MUI a DatePicker
synchroxdev/tooljet-ui pull request #7
Opened 2023-07-31 21:17 UTC by JoseCabrera99

Se crea componente usando la Liberia de MUI para DatePicker.
Se actualiza dependencia @Mui/Material 
Se añade dependencia @mui/x-date-pickers

2023-07-31 23:00 UTC, fredygil requested changes
Saludos Jose Miguel. Gran trabajo con este componente. Dejé unos comentarios, por favor revísalos. Gracias.

2023-07-31 23:00 UTC, fredygil commented on frontend/src/Editor/Components/Datepicker.jsx
> +          <DemoContainer components={['DateTimePicker', 'DateTimePicker']}>
Creo que este `DemoContainer` no se necesita.

2023-07-31 23:00 UTC, fredygil commented on frontend/src/Editor/Components/Datepicker.jsx
> +        <LocalizationProvider dateAdapter={AdapterDayjs}>
Ya que se está usando `LocalizationProvider`, podemos adicionar una propiedad aquí para que muestre los nombres de los meses en Español?

2023-07-31 23:00 UTC, fredygil commented on frontend/src/Editor/Components/Datepicker.jsx
> +      return excludedDates.some((excludedDates) => excludedDates.getTime() === date.$d.getTime());
Es menos confuso si dentro del `some` la variable se llama `excludeDate` (en singular).

2023-08-01 13:32 UTC, JoseCabrera99 commented on frontend/src/Editor/Components/Datepicker.jsx
> +          <DemoContainer components={['DateTimePicker', 'DateTimePicker']}>
Cierto, lo había puesto para ver si con eso me funcionaba algo y olvide cambiarlo

2023-08-01 14:14 UTC, fredygil approved these changes

2023-08-01 14:18 UTC, merged